name: Hexo Build and Deploy

on:
  push:
    branches:
      - master # default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Branch
      uses: actions/checkout@v3

    - name: Create CNAME
      run: |
        mkdir public
        echo 'ho229.lind0.space' > ./public/CNAME

    # Deploy hexo blog website.
    - name: Build and Deploy
      uses: u-u-z/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.TOKEN }}
        PUBLISH_REPOSITORY: ho-229/ho-229.github.io # The repository the action should deploy to.
        BRANCH: gh-page  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.
